In [1]:
import pandas as pd

In [46]:
cached = None

def get_data():
    
    global cached
    
    if cached is None:
        #url="https://www.fhfa.gov/DataTools/Downloads/Documents/HPI/HPI_EXP_state.txt",sep="\t"
        #url="https://www.fhfa.gov/DataTools/Downloads/Documents/HPI/HPI_AT_state.csv"
        url="https://www.fhfa.gov/DataTools/Downloads/Documents/HPI/HPI_PO_state.xls"

        cached = pd.read_excel(url)
        
    return cached

fulldf = get_data()

fulldf.sort_values(by=["yr","qtr"],ascending=False).head(10)

,state,yr,qtr,index_nsa,index_sa,Warning
104,AK,2017,1,248.92,252.49,"* Note that this state has fewer than 15,000 t..."
209,AL,2017,1,207.16,208.34,NaN
314,AR,2017,1,208.40,207.81,NaN
419,AZ,2017,1,281.90,283.19,NaN
524,CA,2017,1,255.85,256.72,NaN
629,CO,2017,1,414.12,415.87,NaN
734,CT,2017,1,165.77,167.56,NaN
839,DC,2017,1,520.78,523.77,"* Note that this state has fewer than 15,000 t..."
944,DE,2017,1,191.78,193.02,"* Note that this state has fewer than 15,000 t..."
1049,FL,2017,1,276.20,277.32,NaN

In [56]:
def us_data():
    return pd.read_excel("https://www.fhfa.gov/DataTools/Downloads/Documents/HPI/HPI_PO_summary.xls")
us_data().sort_values(by=["Year","Quarter"],ascending=False)

,Region,Year,Quarter,Purchase-Only Index (1991Q1=100),Seasonally-Adjusted Purchase-Only Index (1991Q1=100),HPI % Change Over Previous 4 Quarters,HPI % Change Over Previous Quarter,Purchase-Only Index % Change Over Previous 4 Quarters,Purchase-Only Index % Change Over Previous Quarter,Seasonally-Adjusted Purchase-Only Index % Change Over Previous 4 Quarters,Seasonally-Adjusted Purchase-Only Index % Change Over Previous Quarter
104,USA,2017,1,239.58,241.17,0.0549,0.0076,0.0604,0.0078,0.0600,0.0139
103,USA,2016,4,237.73,237.86,0.0574,0.0087,0.0624,0.0017,0.0622,0.0154
102,USA,2016,3,237.32,234.26,0.0582,0.0175,0.0624,0.0158,0.0626,0.0160
101,USA,2016,2,233.62,230.57,0.0570,0.0201,0.0591,0.0340,0.0592,0.0134
100,USA,2016,1,225.93,227.52,0.0552,0.0100,0.0607,0.0097,0.0600,0.0160
99,USA,2015,4,223.77,223.94,0.0553,0.0094,0.0589,0.0017,0.0588,0.0158
98,USA,2015,3,223.38,220.46,0.0542,0.0163,0.0560,0.0127,0.0564,0.0128
97,USA,2015,2,220.59,217.68,0.0526,0.0184,0.0556,0.0356,0.0556,0.0141
96,USA,2015,1,213.01,214.64,0.0537,0.0101,0.0514,0.0080,0.0505,0.0149
95,USA,2014,4,211.32,211.50,0.0527,0.0084,0.0484,-0.0010,0.0486,0.0135
94,USA,2014,3,211.53,208.69,0.0533,0.0147,0.0460,0.0122,0.0462,0.0120
93,USA,2014,2,208.98,206.21,0.0547,0.0195,0.0517,0.0315,0.0516,0.0093
92,USA,2014,1,202.60,204.32,0.0509,0.0090,0.0654,0.0052,0.0646,0.0130
91,USA,2013,4,201.56,201.69,0.0470,0.0090,0.0722,-0.0033,0.0728,0.0112
90,USA,2013,3,202.23,199.47,0.0462,0.0161,0.0779,0.0178,0.0779,0.0172
89,USA,2013,2,198.70,196.10,0.0428,0.0159,0.0724,0.0449,0.0719,0.0218
88,USA,2013,1,190.17,191.92,0.0225,0.0053,0.0676,0.0116,0.0675,0.0208
87,USA,2012,4,187.99,188.01,0.0065,0.0082,0.0507,0.0020,0.0512,0.0160
86,USA,2012,3,187.61,185.06,0.0028,0.0129,0.0368,0.0126,0.0364,0.0116
85,USA,2012,2,185.28,182.94,-0.0024,-0.0039,0.0298,0.0402,0.0291,0.0175
84,USA,2012,1,178.12,179.79,-0.0157,-0.0105,0.0034,-0.0044,0.0039,0.0052
83,USA,2011,4,178.92,178.85,-0.0326,0.0045,-0.0236,-0.0112,-0.0233,0.0016
82,USA,2011,3,180.95,178.56,-0.0439,0.0076,-0.0338,0.0056,-0.0345,0.0045
81,USA,2011,2,179.93,177.76,-0.0420,-0.0172,-0.0541,0.0136,-0.0548,-0.0074
80,USA,2011,1,177.52,179.10,-0.0340,-0.0275,-0.0532,-0.0313,-0.0521,-0.0220
79,USA,2010,4,183.25,183.13,-0.0186,-0.0073,-0.0402,-0.0215,-0.0402,-0.0098
78,USA,2010,3,187.28,184.94,-0.0187,0.0096,-0.0303,-0.0155,-0.0312,-0.0167
77,USA,2010,2,190.23,188.08,-0.0537,-0.0089,-0.0192,0.0146,-0.0198,-0.0045
76,USA,2010,1,187.49,188.94,-0.0705,-0.0120,-0.0305,-0.0180,-0.0293,-0.0097
75,USA,2009,4,190.92,190.79,-0.0523,-0.0073,-0.0242,-0.0115,-0.0244,-0.0006
...,...,...,...,...,...,...,...,...,...,...,...
29,USA,1998,2,123.99,123.12,0.0517,0.0091,0.0456,0.0223,0.0454,0.0141
28,USA,1998,1,121.29,121.40,0.0509,0.0149,0.0396,0.0101,0.0396,0.0123
27,USA,1997,4,120.08,119.93,0.0442,0.0130,0.0330,0.0041,0.0333,0.0108
26,USA,1997,3,119.58,118.65,0.0388,0.0138,0.0280,0.0085,0.0280,0.0074
25,USA,1997,2,118.58,117.78,0.0293,0.0084,0.0277,0.0164,0.0273,0.0085
24,USA,1997,1,116.67,116.78,0.0225,0.0083,0.0256,0.0037,0.0256,0.0062
23,USA,1996,4,116.24,116.07,0.0255,0.0078,0.0280,-0.0007,0.0284,0.0056
22,USA,1996,3,116.32,115.42,0.0255,0.0045,0.0288,0.0081,0.0287,0.0067
21,USA,1996,2,115.39,114.65,0.0367,0.0017,0.0317,0.0143,0.0313,0.0069
20,USA,1996,1,113.76,113.87,0.0518,0.0113,0.0296,0.0060,0.0297,0.0089
19,USA,1995,4,113.08,112.86,0.0456,0.0079,0.0266,0.0001,0.0272,0.0059
18,USA,1995,3,113.07,112.20,0.0366,0.0154,0.0268,0.0110,0.0264,0.0093
17,USA,1995,2,111.84,111.17,0.0251,0.0163,0.0238,0.0122,0.0234,0.0053
16,USA,1995,1,110.49,110.58,0.0147,0.0053,0.0264,0.0031,0.0266,0.0065
15,USA,1994,4,110.15,109.87,0.0158,-0.0008,0.0286,0.0003,0.0292,0.0051
14,USA,1994,3,110.11,109.31,0.0250,0.0041,0.0343,0.0080,0.0338,0.0063
13,USA,1994,2,109.24,108.63,0.0291,0.0061,0.0354,0.0148,0.0350,0.0085
12,USA,1994,1,107.65,107.72,0.0326,0.0064,0.0364,0.0053,0.0367,0.0090
11,USA,1993,4,107.09,106.75,0.0265,0.0083,0.0273,0.0059,0.0278,0.0096
10,USA,1993,3,106.46,105.74,0.0232,0.0081,0.0265,0.0090,0.0260,0.0075
9,USA,1993,2,105.51,104.95,0.0266,0.0095,0.0274,0.0158,0.0272,0.0101
8,USA,1993,1,103.87,103.91,0.0167,0.0004,0.0156,-0.0036,0.0159,0.0004
7,USA,1992,4,104.24,103.87,0.0242,0.0050,0.0273,0.0051,0.0275,0.0079
6,USA,1992,3,103.71,103.06,0.0334,0.0114,0.0289,0.0099,0.0286,0.0087
5,USA,1992,2,102.69,102.17,0.0235,-0.0002,0.0217,0.0042,0.0216,-0.0011
4,USA,1992,1,102.27,102.28,0.0306,0.0077,0.0227,0.0079,0.0228,0.0118
3,USA,1991,4,101.47,101.08,0.0312,0.0141,NaN,0.0067,NaN,0.0089
2,USA,1991,3,100.79,100.19,0.0129,0.0017,NaN,0.0028,NaN,0.0018
1,USA,1991,2,100.52,100.01,0.0173,0.0068,NaN,0.0052,NaN,0.0001
0,USA,1991,1,100.00,100.00,0.0146,0.0083,NaN,NaN,NaN,NaN

# Compare q1 2016 with Q1 2017

In [47]:
df17q1 = fulldf[(fulldf["yr"] == 2017)&(fulldf["qtr"] == 1)].set_index("state")

In [48]:
df16q1 = fulldf[(fulldf["yr"] == 2016)&(fulldf["qtr"] == 1)].set_index("state")

In [49]:
df1617q1 = df16q1.join(df17q1,how="outer",lsuffix="_16",rsuffix="_17").reset_index()

In [50]:
df1617q1["sa_diff"] = df1617q1["index_sa_17"] - df1617q1["index_sa_16"]
df1617q1["sa_growth"] = df1617q1["sa_diff"] * 100 / df1617q1["index_sa_16"]
df1617q1.head(10).sort_values(by="sa_growth",ascending=False)

,state,yr_16,qtr_16,index_nsa_16,index_sa_16,Warning_16,yr_17,qtr_17,index_nsa_17,index_sa_17,Warning_17,sa_diff,sa_growth
7,DC,2016,1,457.53,460.01,"* Note that this state has fewer than 15,000 t...",2017,1,520.78,523.77,"* Note that this state has fewer than 15,000 t...",63.76,13.860568
5,CO,2016,1,373.54,375.56,NaN,2017,1,414.12,415.87,NaN,40.31,10.733305
9,FL,2016,1,252.99,254.11,NaN,2017,1,276.20,277.32,NaN,23.21,9.133840
4,CA,2016,1,238.39,239.29,NaN,2017,1,255.85,256.72,NaN,17.43,7.284049
3,AZ,2016,1,264.11,265.46,NaN,2017,1,281.90,283.19,NaN,17.73,6.678972
1,AL,2016,1,197.50,198.70,NaN,2017,1,207.16,208.34,NaN,9.64,4.851535
2,AR,2016,1,200.41,199.77,NaN,2017,1,208.40,207.81,NaN,8.04,4.024628
0,AK,2016,1,246.42,250.11,"* Note that this state has fewer than 15,000 t...",2017,1,248.92,252.49,"* Note that this state has fewer than 15,000 t...",2.38,0.951581
6,CT,2016,1,164.93,166.74,NaN,2017,1,165.77,167.56,NaN,0.82,0.491784
8,DE,2016,1,192.00,193.40,"* Note that this state has fewer than 15,000 t...",2017,1,191.78,193.02,"* Note that this state has fewer than 15,000 t...",-0.38,-0.196484

Note: The above numbers match this report: https://www.fhfa.gov/AboutUs/Reports/ReportDocuments/2017Q1_HPI.pdf

Good. That means my naive guess about how to calculate growth is correct.

In [53]:
df1617q1["sa_growth"].describe()

count    51.000000
mean      5.449829
std       3.073880
min      -0.196484
25%       3.864937
50%       5.557514
75%       7.316548
max      13.860568
Name: sa_growth, dtype: float64

In [73]:
us_df = us_data()
print us_df.columns

Index([u'Region', u'Year', u'Quarter', u'Purchase-Only Index \n(1991Q1=100)',
       u'Seasonally-Adjusted Purchase-Only Index \n(1991Q1=100)',
       u'HPI\n% Change Over \nPrevious 4 Quarters',
       u'HPI\n% Change Over \nPrevious Quarter',
       u'Purchase-Only Index\n% Change Over \nPrevious 4 Quarters',
       u'Purchase-Only Index\n% Change Over \nPrevious Quarter',
       u'Seasonally-Adjusted Purchase-Only Index\n% Change Over \nPrevious 4 Quarters',
       u'Seasonally-Adjusted Purchase-Only Index\n% Change Over \nPrevious Quarter'],
      dtype='object')

In [130]:
def timeline(df,y_col="Year",q_col="Quarter",
             val_col='Seasonally-Adjusted Purchase-Only Index \n(1991Q1=100)',
            index_col="Region"):
    ret = df.copy()
    
    #ret ["y-q"] = ret.apply(lambda x: str(x["Year"]) + "-" + str(x["Quarter"]),axis=1)

    ret = ret[ret[q_col] == 1]
    ret = ret.pivot(columns=y_col,
                    values=val_col,
                    index=index_col)\
    .reset_index()\
    .transpose()
    
    
    ret = ret.reset_index()#.set_index("y-q")

    ret.columns = "year","index"
    ret = ret.drop(0)
    
    ret = ret.set_index("year")
    
    return ret

us_timeline = timeline(us_df)

In [131]:
ct_timeline = timeline(fulldf[fulldf["state"] == "CT"],q_col="qtr",y_col="yr",val_col="index_sa",index_col="state")

In [132]:
print ct_timeline.join(us_timeline,how="outer",lsuffix="_CT",rsuffix="_US").to_csv(sep="\t")

year	index_CT	index_US
1991	100.0	100.0
1992	97.39	102.28
1993	92.62	103.91
1994	91.57	107.72
1995	90.86	110.58
1996	91.2	113.87
1997	91.3	116.78
1998	94.06	121.4
1999	101.96	128.65
2000	110.89	136.99
2001	120.95	146.68
2002	133.2	156.29
2003	149.87	168.41
2004	163.97	182.48
2005	183.51	201.53
2006	197.41	219.98
2007	198.47	224.54
2008	190.62	212.38
2009	179.42	194.63
2010	171.55	188.94
2011	165.43	179.1
2012	160.47	179.79
2013	161.43	191.92
2014	164.74	204.32
2015	165.59	214.64
2016	166.74	227.52
2017	167.56	241.17

In [133]:
states_pct_df = df1617q1.sort_values(by="sa_growth",ascending=True)[["state","sa_growth"]].set_index("state")
states_pct_df["sa_growth"] = states_pct_df["sa_growth"].apply(lambda x: round(x,2))
states_pct_df["sa_growth"] = states_pct_df["sa_growth"].astype(str) + "%"
states_pct_df
print states_pct_df.to_csv(sep="\t")

state	sa_growth
DE	-0.2%
ND	-0.07%
WV	0.45%
CT	0.49%
HI	0.77%
AK	0.95%
MS	1.52%
WY	1.81%
LA	2.04%
NJ	2.69%
SC	3.39%
VA	3.7%
MD	3.84%
MT	3.89%
MO	3.91%
OK	3.93%
PA	3.95%
AR	4.02%
OH	4.51%
IA	4.53%
IN	4.62%
ME	4.73%
AL	4.85%
NY	4.92%
KS	5.35%
WI	5.56%
SD	5.63%
NM	5.69%
IL	5.7%
MN	6.01%
KY	6.33%
NC	6.34%
RI	6.47%
MA	6.56%
GA	6.59%
AZ	6.68%
TX	7.15%
CA	7.28%
NE	7.35%
VT	7.74%
MI	7.8%
TN	7.87%
UT	8.78%
NV	8.88%
FL	9.13%
OR	9.14%
NH	9.55%
WA	10.23%
ID	10.3%
CO	10.73%
DC	13.86%

In [135]:
fulldf[(fulldf["state"]=="CT")].sort_values(by="index_sa",ascending=False)

    state    yr  qtr  index_nsa  index_sa Warning
694    CT  2007    1     196.72    198.47     NaN
690    CT  2006    1     195.62    197.41     NaN
691    CT  2006    2     199.98    197.33     NaN
696    CT  2007    3     199.34    196.90     NaN
695    CT  2007    2     198.91    196.18     NaN
693    CT  2006    4     194.63    195.53     NaN
692    CT  2006    3     197.71    195.27     NaN
689    CT  2005    4     194.02    194.79     NaN
697    CT  2007    4     193.26    194.09     NaN
688    CT  2005    3     193.87    191.27     NaN
698    CT  2008    1     188.73    190.62     NaN
687    CT  2005    2     189.75    187.58     NaN
699    CT  2008    2     190.09    187.40     NaN
700    CT  2008    3     186.18    183.89     NaN
686    CT  2005    1     181.76    183.51     NaN
701    CT  2008    4     180.53    181.10     NaN
702    CT  2009    1     177.31    179.42     NaN
685    CT  2004    4     178.59    179.01     NaN
703    CT  2009    2     178.57    175.97     NaN
684    CT  2004    3     177.53    175.02     NaN
704    CT  2009    3     177.03    174.80     NaN
705    CT  2009    4     173.03    173.26     NaN
706    CT  2010    1     169.00    171.55     NaN
707    CT  2010    2     173.37    170.65     NaN
683    CT  2004    2     170.85    169.18     NaN
708    CT  2010    3     170.43    168.19     NaN
733    CT  2016    4     166.78    167.72     NaN
734    CT  2017    1     165.77    167.56     NaN
709    CT  2010    4     166.79    166.84     NaN
730    CT  2016    1     164.93    166.74     NaN
..    ...   ...  ...        ...       ...     ...
631    CT  1991    2      97.82     98.04     NaN
660    CT  1998    3      98.60     97.53     NaN
634    CT  1992    1      97.30     97.39     NaN
632    CT  1991    3      97.08     96.28     NaN
633    CT  1991    4      96.58     95.89     NaN
659    CT  1998    2      96.38     95.59     NaN
635    CT  1992    2      95.22     95.42     NaN
637    CT  1992    4      96.03     95.37     NaN
636    CT  1992    3      95.11     94.24     NaN
658    CT  1998    1      93.41     94.06     NaN
657    CT  1997    4      93.39     93.33     NaN
638    CT  1993    1      92.40     92.62     NaN
656    CT  1997    3      93.53     92.48     NaN
655    CT  1997    2      92.65     92.00     NaN
643    CT  1994    2      91.89     91.84     NaN
644    CT  1994    3      92.82     91.75     NaN
639    CT  1993    2      91.59     91.70     NaN
642    CT  1994    1      91.20     91.57     NaN
651    CT  1996    2      91.95     91.46     NaN
645    CT  1994    4      91.85     91.45     NaN
640    CT  1993    3      92.38     91.41     NaN
641    CT  1993    4      91.93     91.39     NaN
654    CT  1997    1      90.70     91.30     NaN
650    CT  1996    1      90.63     91.20     NaN
652    CT  1996    3      91.99     90.92     NaN
646    CT  1995    1      90.37     90.86     NaN
649    CT  1995    4      91.02     90.79     NaN
648    CT  1995    3      91.89     90.79     NaN
653    CT  1996    4      90.84     90.73     NaN
647    CT  1995    2      90.68     90.43     NaN

[105 rows x 6 columns]